#!/bin/bash

#
# gerrit-query uninstall - remove gerrit-query configuration
#

CONFIG_DIR="$HOME/.config/gerrit-query"

if [ -d "$CONFIG_DIR" ]; then
    rm -rf "$CONFIG_DIR"
    echo "[gerrit-query] uninstall: removed $CONFIG_DIR"
else
    echo "[gerrit-query] uninstall: nothing to remove."
fi